apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- admissionregistration.k8s.io_v1_mutatingwebhookconfiguration_iventure-kube-prometheus-s-admission.yaml
- admissionregistration.k8s.io_v1_validatingwebhookconfiguration_iventure-kube-prometheus-s-admission.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_alertmanagerconfigs.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_alertmanagers.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_podmonitors.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_probes.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_prometheusagents.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_prometheuses.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_prometheusrules.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_scrapeconfigs.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_servicemonitors.monitoring.coreos.com.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_thanosrulers.monitoring.coreos.com.yaml
- apps_v1_daemonset_iventure-prometheus-node-exporter.yaml
- apps_v1_deployment_iventure-grafana.yaml
- apps_v1_deployment_iventure-kube-prometheus-s-operator.yaml
- apps_v1_deployment_iventure-kube-state-metrics.yaml
- batch_v1_job_iventure-kube-prometheus-s-admission-create.yaml
- batch_v1_job_iventure-kube-prometheus-s-admission-patch.yaml
- monitoring.coreos.com_v1_alertmanager_iventure-kube-prometheus-s-alertmanager.yaml
- monitoring.coreos.com_v1_prometheus_iventure-kube-prometheus-s-prometheus.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-alertmanager.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-config-reloaders.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-etcd.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-general.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-k8s.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-apiserver-availability.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-apiserver-burnrate.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-apiserver-histogram.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-apiserver-slos.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-prometheus-general.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-prometheus-node-recording.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-scheduler.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kube-state-metrics.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubelet.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-apps.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-resources.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-storage.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-system-apiserver.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-system-controller-manager.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-system-kube-proxy.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-system-kubelet.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-system-scheduler.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-kubernetes-system.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-node-exporter.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-node-exporter.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-node-network.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-node.rules.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-prometheus-operator.yaml
- monitoring.coreos.com_v1_prometheusrule_iventure-kube-prometheus-s-prometheus.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-grafana.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-alertmanager.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-apiserver.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-coredns.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-kube-controller-manager.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-kube-etcd.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-kube-proxy.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-kube-scheduler.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-kubelet.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-operator.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-prometheus-s-prometheus.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-kube-state-metrics.yaml
- monitoring.coreos.com_v1_servicemonitor_iventure-prometheus-node-exporter.yaml
- rbac.authorization.k8s.io_v1_clusterrole_iventure-grafana-clusterrole.yaml
- rbac.authorization.k8s.io_v1_clusterrole_iventure-kube-prometheus-s-admission.yaml
- rbac.authorization.k8s.io_v1_clusterrole_iventure-kube-prometheus-s-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrole_iventure-kube-prometheus-s-prometheus.yaml
- rbac.authorization.k8s.io_v1_clusterrole_iventure-kube-state-metrics.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_iventure-grafana-clusterrolebinding.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_iventure-kube-prometheus-s-admission.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_iventure-kube-prometheus-s-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_iventure-kube-prometheus-s-prometheus.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_iventure-kube-state-metrics.yaml
- rbac.authorization.k8s.io_v1_role_iventure-grafana.yaml
- rbac.authorization.k8s.io_v1_role_iventure-kube-prometheus-s-admission.yaml
- rbac.authorization.k8s.io_v1_rolebinding_iventure-grafana.yaml
- rbac.authorization.k8s.io_v1_rolebinding_iventure-kube-prometheus-s-admission.yaml
- v1_configmap_iventure-grafana-config-dashboards.yaml
- v1_configmap_iventure-grafana-test.yaml
- v1_configmap_iventure-grafana.yaml
- v1_configmap_iventure-kube-prometheus-s-grafana-datasource.yaml
- v1_persistentvolumeclaim_iventure-grafana.yaml
- v1_pod_iventure-grafana-test.yaml
- v1_secret_alertmanager-iventure-kube-prometheus-s-alertmanager.yaml
- v1_secret_iventure-grafana.yaml
- v1_service_iventure-grafana.yaml
- v1_service_iventure-kube-prometheus-s-alertmanager.yaml
- v1_service_iventure-kube-prometheus-s-coredns.yaml
- v1_service_iventure-kube-prometheus-s-kube-controller-manager.yaml
- v1_service_iventure-kube-prometheus-s-kube-etcd.yaml
- v1_service_iventure-kube-prometheus-s-kube-proxy.yaml
- v1_service_iventure-kube-prometheus-s-kube-scheduler.yaml
- v1_service_iventure-kube-prometheus-s-operator.yaml
- v1_service_iventure-kube-prometheus-s-prometheus.yaml
- v1_service_iventure-kube-state-metrics.yaml
- v1_service_iventure-prometheus-node-exporter.yaml
- v1_serviceaccount_iventure-grafana-test.yaml
- v1_serviceaccount_iventure-grafana.yaml
- v1_serviceaccount_iventure-kube-prometheus-s-admission.yaml
- v1_serviceaccount_iventure-kube-prometheus-s-alertmanager.yaml
- v1_serviceaccount_iventure-kube-prometheus-s-operator.yaml
- v1_serviceaccount_iventure-kube-prometheus-s-prometheus.yaml
- v1_serviceaccount_iventure-kube-state-metrics.yaml
- v1_serviceaccount_iventure-prometheus-node-exporter.yaml
