apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.0.2
    chart: kube-prometheus-stack-51.0.2
    heritage: Helm
    release: iventure
  name: iventure-kube-prometheus-s-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iventure-kube-prometheus-s-operator
subjects:
- kind: ServiceAccount
  name: iventure-kube-prometheus-s-operator
  namespace: monitoring
