apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.1.1
    helm.sh/chart: grafana-6.59.4
  name: iventure-grafana-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: iventure-grafana-clusterrole
subjects:
- kind: ServiceAccount
  name: iventure-grafana
  namespace: monitoring
