apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.0.2
    chart: kube-prometheus-stack-51.0.2
    heritage: Helm
    release: iventure
  name: iventure-kube-prometheus-s-operator
  namespace: monitoring
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    app: kube-prometheus-stack-operator
    release: iventure
  type: ClusterIP
