apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-coredns
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.0.2
    chart: kube-prometheus-stack-51.0.2
    heritage: Helm
    jobLabel: coredns
    release: iventure
  name: iventure-kube-prometheus-s-coredns
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
