apiVersion: v1
data:
  admin-password: WW9zY3p4Y1NteEtNRUZjZHNHSlBLbVg5RWRoaGJURW9ZZ3dyQTdEVA==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.1.1
    helm.sh/chart: grafana-6.59.4
  name: iventure-grafana
  namespace: monitoring
type: Opaque
