apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.6.1
    helm.sh/chart: prometheus-node-exporter-4.23.0
    jobLabel: node-exporter
    release: iventure
  name: iventure-prometheus-node-exporter
  namespace: monitoring
spec:
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/name: prometheus-node-exporter
  type: ClusterIP
