apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.0.2
    chart: kube-prometheus-stack-51.0.2
    heritage: Helm
    release: iventure
    self-monitor: "true"
  name: iventure-kube-prometheus-s-alertmanager
  namespace: monitoring
spec:
  ports:
  - name: http-web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - appProtocol: http
    name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    alertmanager: iventure-kube-prometheus-s-alertmanager
    app.kubernetes.io/name: alertmanager
  type: ClusterIP
