apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: iventure
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 51.0.2
    chart: kube-prometheus-stack-51.0.2
    heritage: Helm
    jobLabel: kube-etcd
    release: iventure
  name: iventure-kube-prometheus-s-kube-etcd
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2381
    protocol: TCP
    targetPort: 2381
  selector:
    component: etcd
  type: ClusterIP
