resources:
- ../../kube-prometheus 



patches:
  - path: delete-crds.yaml
  - path: prometheus-additional-scrape.yaml
  - path: grafana-env-patch.yaml
  - path: grafana-datasource-patch.yaml                          

secretGenerator:
- name: additional-scrape-configs
  namespace: monitoring
  files:
  - prometheus-additional-scrape.yaml
  options:
    disableNameSuffixHash: true  
    
- name: grafana-admin-credentials
  namespace: monitoring
  literals:
    - admin-user=admin
    - admin-password=iventure@2025
  options:
      disableNameSuffixHash: true  