resources:
- ../../kube-prometheus 
      
patchesStrategicMerge:
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: prometheuses.monitoring.coreos.com
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: prometheusagents.monitoring.coreos.com
    $patch: delete
  - |-
    apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    metadata:
      name: iventure-kube-prometheus-s-prometheus
      namespace: monitoring
    spec:
      additionalScrapeConfigs:
        name: additional-scrape-configs
        key: prometheus-additional-scrape.yaml
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: iventure-grafana
      namespace: monitoring
    spec:
      template:
        spec:
          containers:
          - name: grafana
            env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-password
          - name: grafana-sc-datasources
            env:
            - name: REQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-user
            - name: REQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-password
          - name: grafana-sc-dashboard
            env:
            - name: REQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-user
            - name: REQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin-credentials
                  key: admin-password
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: iventure-kube-prometheus-s-grafana-datasource
      namespace: monitoring
      labels:
        grafana_datasource: "1"
    data:
      datasource.yaml: |
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus
          url: http://iventure-kube-prometheus-s-prometheus.monitoring.svc.cluster.local:9090
          access: proxy
          isDefault: true
          jsonData:
            httpMethod: POST
            timeInterval: 30s
        - name: Alertmanager
          type: alertmanager
          uid: alertmanager
          url: http://iventure-kube-prometheus-s-alertmanager.monitoring.svc.cluster.local:9093
          access: proxy
          jsonData:
            handleGrafanaManagedAlerts: false
            implementation: prometheus
                        

secretGenerator:
- name: additional-scrape-configs
  namespace: monitoring
  files:
  - prometheus-additional-scrape.yaml
  options:
    disableNameSuffixHash: true  
    
- name: grafana-admin-credentials
  namespace: monitoring
  literals:
    - admin-user=admin
    - admin-password=iventure@2025
  options:
      disableNameSuffixHash: true  